# Based upon https://github.com/arturbosch/detekt/blob/master/detekt-cli/src/main/resources/default-detekt-config.yml

build:
  maxIssues: 0

complexity:
  ComplexInterface:
    active: true
  LabeledExpression:
    active: true
  LongMethod:
    active: true
    threshold: 60
  MethodOverloading:
    active: true

exceptions:
  ExceptionRaisedInUnexpectedLocation:
    active: true
  InstanceOfCheckForException:
    active: true
  PrintStackTrace:
    active: true
  RethrowCaughtException:
    active: true
  ReturnFromFinally:
    active: true
  SwallowedException:
    active: true
  ThrowingExceptionFromFinally:
    active: true
  ThrowingExceptionInMain:
    active: true
  ThrowingExceptionsWithoutMessageOrCause:
    active: true
  ThrowingNewInstanceOfSameException:
    active: true

formatting:
  Indentation:
    active: true
  MaximumLineLength:    # Covered by style.MaxLineLength (which ignores import statements)
    active: false

naming:
  MemberNameEqualsClassName:
    active: true

performance:
  ArrayPrimitive:
    active: true

potential-bugs:
  EqualsAlwaysReturnsTrueOrFalse:
    active: true
  InvalidRange:
    active: true
  IteratorHasNextCallsNextMethod:
    active: true
  IteratorNotThrowingNoSuchElementException:
    active: true
  UnconditionalJumpStatementInLoop:
    active: true
  UselessPostfixExpression:
    active: true
  WrongEqualsTypeParameter:
    active: true

style:
  EqualsOnSignatureLine:
    active: true
  ExplicitItLambdaParameter:
    active: true
  ForbiddenVoid:
    active: true
  FunctionOnlyReturningConstant:
    active: true
  MandatoryBracesIfStatements:
    active: true
  NoTabs:
    active: true
  OptionalUnit:
    active: true
  OptionalWhenBraces:
    active: true
  ProtectedMemberInFinalClass:
    active: true
  RedundantVisibilityModifierRule:
    active: true
  SpacingBetweenPackageAndImports:
    active: true
  UnderscoresInNumericLiterals:
    active: true
  UnnecessaryApply:
    active: true
  UnnecessaryInheritance:
    active: true
  UnnecessaryLet:
    active: true
  UntilInsteadOfRangeTo:
    active: true
  UnusedImports:
    active: true
  UnusedPrivateClass:
    active: true
  UtilityClassWithPublicConstructor:
    active: true
  VarCouldBeVal:
    active: true
